@ECHO OFF

REM Gracelite/admin_dbprod_shpcsv-in_insert_ogr2ogr.bat
REM Version : 0.01
REM ALENO
REM INSERTION DES DONNEES SHPCSV-IN DANS gracelite_prod.sqlite
REM Licence : GNU GPLv3
REM 19/06/2015 - SBY - aleno.eu : CREATION DU SCRIPT
REM Cible spatialite


ECHO INSERTION DES DONNEES SHPCSV-IN DANS gracelite_prod.sqlite
PAUSE

CALL config.bat
REM FOR %%f IN ("%GLOSGEOPATH%\etc\ini\*.bat") DO CALL "%%f"

REM CHEMIN VERS ogr2ogr.exe
REM SET GLOGR2OGR=C:\Program Files\QGIS Wien\bin
REM SET GLOGR2OGR=C:\OSGeo4w\bin

REM ogr2ogr -append .\dbPROD\gracelite_PROD.sqlite .\shpcsv-in\t_adresse.shp -nln t_adresse
REM ogr2ogr -append .\dbPROD\gracelite_PROD.sqlite .\shpcsv-in\t_organisme.csv -nln t_organisme


SET GLTBL=t_adresse
SET GLFILE=%GLSHPINPATH%\%GLTBL%.shp
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_organisme
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_reference
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_noeud
SET GLFILE=%GLSHPINPATH%\%GLTBL%.shp
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_sitetech
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_ltech
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_baie
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_tiroir
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_equipement
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_suf
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_ptech
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_ebp
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_cassette
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_cheminement
SET GLFILE=%GLSHPINPATH%\%GLTBL%.shp
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_conduite
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_cond_chem
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_masque
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_cable
SET GLFILE=%GLSHPINPATH%\%GLTBL%.shp
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_cab_cond
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_love
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_fibre
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_position
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_ropt
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_siteemission
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_znro
SET GLFILE=%GLSHPINPATH%\%GLTBL%.shp
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL% -nlt PROMOTE_TO_MULTI

SET GLTBL=t_zsro
SET GLFILE=%GLSHPINPATH%\%GLTBL%.shp
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL% -nlt PROMOTE_TO_MULTI

SET GLTBL=t_zpbo
SET GLFILE=%GLSHPINPATH%\%GLTBL%.shp
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL% -nlt PROMOTE_TO_MULTI

SET GLTBL=t_zdep
SET GLFILE=%GLSHPINPATH%\%GLTBL%.shp
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL% -nlt PROMOTE_TO_MULTI

SET GLTBL=t_zcoax
SET GLFILE=%GLSHPINPATH%\%GLTBL%.shp
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL% -nlt PROMOTE_TO_MULTI

SET GLTBL=t_document
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_docobj
SET GLFILE=%GLSHPINPATH%\%GLTBL%.csv
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL%

SET GLTBL=t_empreinte
SET GLFILE=%GLSHPINPATH%\%GLTBL%.shp
ECHO GRACELITE - INSERT %GLFILE%
IF EXIST "%GLFILE%" "%GLOGR2OGR%" -append %GLDBPROD% "%GLFILE%" -nln %GLTBL% -nlt PROMOTE_TO_MULTI

PAUSE
