@ECHO OFF

REM ### CONFIG BINAIRES - CHEMINS ABSOLUS
REM GLOSGEOPATH - Chemin du dossier d'installation de QGIS / OSGeo4w (OSGeo4W.bat doit y etre present)
SET GLOSGEOPATH=C:\Program Files\QGIS Wien
REM SET GLOSGEOPATH=C:\OSGeo4W
REM GLQGIS - Chemin vers qgis.bat
SET GLQGIS=%GLOSGEOPATH%\bin\qgis.bat
REM GLOGRINIT - Initialisation des variables d'environnement pour executer GDAL/OGR
SET GLOSGEO4W=%GLOSGEOPATH%\OSGeo4W.bat
REM GLOGR2OGR - Chemin vers ogr2ogr.exe
SET GLOGR2OGR=%GLOSGEOPATH%\bin\ogr2ogr.exe
SET GLOGRINFO=%GLOSGEOPATH%\bin\ogrinfo.exe
SET GLNOTEPAD=notepad

REM ### CONFIG BINAIRES - CHEMINS RELATIFS
SET GLSPLEX=spatialite.exe --silent
SET GLSPLTOOL=spatialite_tool.exe
SET GLSPLGUI=spatialite_gui.exe
SET GLSHP_DOCTOR=shp_doctor.exe
SET GLSFK=sfk174.exe
SET GL7Z=7z.exe

REM ### CONFIG DBINTEG SPATIALITE
SET GLDBINTEG=.\dbinteg\gracelite_integ.sqlite
SET GLDBINTEGSCHEMA=.\sql_spatialite

REM ### CONFIG DBPROD SPATIALITE
SET GLDBPROD=.\dbprod\gracelite_prod.sqlite
SET GLDBPRODSCHEMA=.\sql_spatialite

REM ### CONFIG SHPCSV-IN
SET GLSHPINPATH=.\shpcsv-in
REM # CONFIG SPATIALITE_TOOL
SET GLSHPINSRID=2154
SET GLSHPINCODE=CP1252
SET GLCSVINCODE=UTF-8
SET GLCSVINQUOTE=NONE
SET GLCSVINDELIM=;

REM ### CONFIG SHPCSV-OUT
SET GLSHPOUTPATH=.\shpcsv-out
REM # CONFIG SPATIALITE_TOOL
SET GLSHPOUTSRID=2154
SET GLSHPOUTCODE=CP1252
SET GLCSVOUTCODE=UTF-8
SET GLCSVOUTQUOTE=NONE
SET GLCSVOUTDELIM=;

REM ### CONFIG DBPROD POSTGIS
REM # CONFIG VARIABLES POSTGRESQL
REM Configurer pgpassword et user. 
SET PGPASSWORD=MYPASSWORD
REM VARIABLE POSTGRESQL POUR FIXER L'ENCODAGE DES SORTIES (PGSQL2SHP). NON TESTE. 
SET pgclientencoding=WIN1252
REM # CONFIG BATCH
SET PGHOSTNAME=localhost
SET PGPORT=5432
SET PGDB=gracethd2beta2b
SET PGSCHEMA=gracethd
SET PGUSER=postgres
REM SET PGSRC=D:\postgres_files\shpcsv-out
SET PGSHPINPATH=D:\postgres_files\shpcsv-in
SET PGSHPOUTPATH=D:\postgres_files\shpcsv-out
SET PGSRID=2154
SET PGCODE=cp1252
SET PGCSVCONF= WITH DELIMITER ';' CSV HEADER ENCODING 'UTF8'


