@ECHO OFF

REM TODO : Utiliser un veritable fichier de conf. 

:LAUNCH
CALL:CONF
ECHO Gracepg - Export PostGIS vers SHP CSV. 
CALL:EXPORT
PAUSE
GOTO:EOF

:CONF
CALL config.bat

GOTO:EOF

:OK
REM Pour placer les commandes deja passees quand ca coince
GOTO:EOF

:EXPORT

REM pgsql2shp -f "D:\postgres_files\shpcsv-out\t_adresse" -h localhost -p 5433 -u postgres -P MYPASSWORD gracethd-v2-beta1b gracethd.t_zcoax

SET PGTBL=t_adresse
SET PGSHP=%PGSHPOUTPATH%\%PGTBL%
pgsql2shp -f %PGSHP% -h %PGHOSTNAME% -p %PGPORT% -u %PGUSER% -P %PGPASSWORD% %PGDB% %PGSCHEMA%.%PGTBL%
PAUSE

SET PGTBL=t_organisme
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_reference
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_noeud
SET PGSHP=%PGSHPOUTPATH%\%PGTBL%
pgsql2shp -f %PGSHP% -h %PGHOSTNAME% -p %PGPORT% -u %PGUSER% -P %PGPASSWORD% %PGDB% %PGSCHEMA%.%PGTBL%

SET PGTBL=t_sitetech
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_ltech
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_baie
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_tiroir
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_equipement
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_suf
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_ptech
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_ebp
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_cassette
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_cheminement
SET PGSHP=%PGSHPOUTPATH%\%PGTBL%
pgsql2shp -f %PGSHP% -h %PGHOSTNAME% -p %PGPORT% -u %PGUSER% -P %PGPASSWORD% %PGDB% %PGSCHEMA%.%PGTBL%

SET PGTBL=t_conduite
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_cond_chem
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_masque
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_cable
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_cableline
SET PGSHP=%PGSHPOUTPATH%\%PGTBL%
pgsql2shp -f %PGSHP% -h %PGHOSTNAME% -p %PGPORT% -u %PGUSER% -P %PGPASSWORD% %PGDB% %PGSCHEMA%.%PGTBL%

SET PGTBL=t_cab_cond
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_love
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_fibre
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_position
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_ropt
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_siteemission
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_znro
SET PGSHP=%PGSHPOUTPATH%\%PGTBL%
pgsql2shp -f %PGSHP% -h %PGHOSTNAME% -p %PGPORT% -u %PGUSER% -P %PGPASSWORD% %PGDB% %PGSCHEMA%.%PGTBL%

SET PGTBL=t_zsro
SET PGSHP=%PGSHPOUTPATH%\%PGTBL%
pgsql2shp -f %PGSHP% -h %PGHOSTNAME% -p %PGPORT% -u %PGUSER% -P %PGPASSWORD% %PGDB% %PGSCHEMA%.%PGTBL%

SET PGTBL=t_zpbo
SET PGSHP=%PGSHPOUTPATH%\%PGTBL%
pgsql2shp -f %PGSHP% -h %PGHOSTNAME% -p %PGPORT% -u %PGUSER% -P %PGPASSWORD% %PGDB% %PGSCHEMA%.%PGTBL%

SET PGTBL=t_zdep
SET PGSHP=%PGSHPOUTPATH%\%PGTBL%
pgsql2shp -f %PGSHP% -h %PGHOSTNAME% -p %PGPORT% -u %PGUSER% -P %PGPASSWORD% %PGDB% %PGSCHEMA%.%PGTBL%

SET PGTBL=t_zcoax
SET PGSHP=%PGSHPOUTPATH%\%PGTBL%
pgsql2shp -f %PGSHP% -h %PGHOSTNAME% -p %PGPORT% -u %PGUSER% -P %PGPASSWORD% %PGDB% %PGSCHEMA%.%PGTBL%

SET PGTBL=t_document
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_docobj
SET PGCSV=%PGSHPOUTPATH%\%PGTBL%.csv
PSQL -h %PGHOSTNAME% -p %PGPORT% -c "COPY %PGSCHEMA%.%PGTBL% TO '%PGCSV%' %PGCSVCONF%;" -d %PGDB% %PGUSER%

SET PGTBL=t_empreinte
SET PGSHP=%PGSHPOUTPATH%\%PGTBL%
pgsql2shp -f %PGSHP% -h %PGHOSTNAME% -p %PGPORT% -u %PGUSER% -P %PGPASSWORD% %PGDB% %PGSCHEMA%.%PGTBL%


GOTO:EOF

:NOK
REM Pour placer des commandes en attente, quand ca coince. 


GOTO:EOF

