/*Gracelite/gracelite_schema*/
/*Version : 0.0.1*/
/*ALENO*/
/*CREATION DU SCHEMA DE gracelite*/
/*Licence : GNU GPLv3*/
/*18/0/2015 - SBY - aleno.eu : CREATION DU SCRIPT*/
/*Cible spatialite*/


/*###################################*/
/*SUPPRESSION TABLES*/
DROP TABLE IF EXISTS t_cable;
DROP TABLE IF EXISTS t_ebp;

/*####################################################*/
/*ENUMERATIONS*/


/*####################################################*/
/*LISTES*/


/*####################################################*/
/*TABLES*/
CREATE TABLE t_cable(
CA_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
ID_INSEE	VARCHAR(80),
AR_VOIE	VARCHAR(80),
AR_TYP_IMP	VARCHAR(80),
AR_TYP_LGQ	VARCHAR(80),
AR_ETAT	VARCHAR(80),
AR_OCCP	VARCHAR(80),
NOEUD_A	VARCHAR(80),
NOEUD_B	VARCHAR(80),
NB_FOUR	VARCHAR(80),
NB_FOUR_DI	VARCHAR(80),
NB_FST	VARCHAR(80),
NB_CABLE	VARCHAR(80),
NB_FIBRE	DOUBLE,
NB_UTIL	VARCHAR(80),
REF_PLANCH	VARCHAR(80),
DATE_INST	VARCHAR(80),
AR_LONG	DOUBLE,
NB_FIB_UTI	DOUBLE,
TYPE_CABLE	VARCHAR(80),
TECH_CABLE	VARCHAR(80),
DIAM_CABLE	DOUBLE,
ETAT_CABLE	VARCHAR(80),
PRO_CABLE	VARCHAR(80),
GEST_CABLE	VARCHAR(80),
UTIL_CABLE	VARCHAR(80),
AR_SRC_GEO	VARCHAR(80),
AR_QLT_GEO	VARCHAR(80),
AR_PRO_MD	VARCHAR(80),
COMMENT	VARCHAR(80),
AV_CABLE	VARCHAR(80),
NOM_CABLE	VARCHAR(80),
LOVE_CABLE	VARCHAR(80)
);

CREATE TABLE t_ebp(
EP_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
NO_NOM	VARCHAR(80),
NO_OCCP	VARCHAR(80),
NO_TYPE_LQ	VARCHAR(80),
NO_TYPE_PH	VARCHAR(80),
TECH_PSTES	VARCHAR(80),
NO_ACCESS	VARCHAR(80),
NO_PLINOX	VARCHAR(80),
NB_EP	VARCHAR(80),
NO_HAUT	VARCHAR(80),
REF_PLANCH	VARCHAR(80),
NO_SRC_GEO	VARCHAR(80),
NO_QLT_GEO	VARCHAR(80),
NO_PRO_MD	VARCHAR(80),
ID_INSEE	VARCHAR(80),
NO_VOIE	VARCHAR(80),
NO_ETAT	VARCHAR(80),
TYPE_EP	VARCHAR(80),
NO_PRO	VARCHAR(80),
NO_GEST	VARCHAR(80),
NO_TYPE	VARCHAR(80),
DATE_INST	VARCHAR(80),
COMMENT	VARCHAR(80),
NO_UTIL	VARCHAR(80),
NO_AVANC	VARCHAR(80),
NO_CONSTRU	VARCHAR(80),
NO_CAPAMAX	DOUBLE,
NO_NBEPISS	DOUBLE,
NO_CONTENA	VARCHAR(80),
NO_DOSSIER	VARCHAR(80)
);

SELECT AddGeometryColumn('t_cable','Geometry', 2154, 'LINESTRING', 'XY');
SELECT CreateSpatialIndex('t_cable','Geometry');
SELECT AddGeometryColumn('t_ebp','Geometry', 2154, 'POINT', 'XY');
SELECT CreateSpatialIndex('t_ebp','Geometry');
