@ECHO OFF

:VARIABLES
REM SET SPLEX=..\..\bin\spatialite41\spatialite.exe
REM SET SPLEX=..\..\tools\spatialite42\spatialite.exe
SET SPLEX=spatialite.exe
SET SPLDB=.\dbinteg\gracelite_integ.sqlite
SET SHPDB=.\shpcsv-in\

:BASE
ECHO SUPPRESSION BASE
IF EXIST %SPLDB% DEL /s %SPLDB%

ECHO CREATION BASE
%SPLEX% %SPLDB% "PRAGMA foreign_keys = ON;"

:CONNECTSHP
ECHO CONNEXION SOURCES EXTERNES
REM %SPLEX% %SPLDB% "CREATE VIRTUAL TABLE 'vt_shpsupport' USING VirtualShape('%SHPDB%Les supports', 'CP1252', 2154);"
SET SHP=Aerien
SET SPLVT=vt_shpaerien
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%SHPDB%%SHP%', 'CP1252', 2154);"
IF EXIST "%SHPDB%%SHP%.shp" %SPLEX% %SPLDB% %SPLSQL%

SET SHP=Artere
SET SPLVT=vt_shpartere
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%SHPDB%%SHP%', 'CP1252', 2154);"
IF EXIST "%SHPDB%%SHP%.shp" %SPLEX% %SPLDB% %SPLSQL%

SET SHP=Cable
SET SPLVT=vt_shpcable
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%SHPDB%%SHP%', 'CP1252', 2154);"
IF EXIST "%SHPDB%%SHP%.shp" %SPLEX% %SPLDB% %SPLSQL%

SET SHP=Chambre
SET SPLVT=vt_shpchambre
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%SHPDB%%SHP%', 'CP1252', 2154);"
IF EXIST "%SHPDB%%SHP%.shp" %SPLEX% %SPLDB% %SPLSQL%

SET SHP=Ebp
SET SPLVT=vt_shpebp
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%SHPDB%%SHP%', 'CP1252', 2154);"
IF EXIST "%SHPDB%%SHP%.shp" %SPLEX% %SPLDB% %SPLSQL%

SET SHP=Fourreau
SET SPLVT=vt_shpfourreau
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%SHPDB%%SHP%', 'CP1252', 2154);"
IF EXIST "%SHPDB%%SHP%.shp" %SPLEX% %SPLDB% %SPLSQL%

SET SHP=LocauxTechniques
SET SPLVT=vt_shplocauxtechniques
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%SHPDB%%SHP%', 'CP1252', 2154);"
IF EXIST "%SHPDB%%SHP%.shp" %SPLEX% %SPLDB% %SPLSQL%

SET SHP=Site
SET SPLVT=vt_shpsite
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%SHPDB%%SHP%', 'CP1252', 2154);"
IF EXIST "%SHPDB%%SHP%.shp" %SPLEX% %SPLDB% %SPLSQL%

SET SHP=Tranchee
SET SPLVT=vt_shptranchee
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%SHPDB%%SHP%', 'CP1252', 2154);"
IF EXIST "%SHPDB%%SHP%.shp" %SPLEX% %SPLDB% %SPLSQL%

SET SHP=Zpbo
SET SPLVT=vt_shpzpbo
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%SHPDB%%SHP%', 'CP1252', 2154);"
IF EXIST "%SHPDB%%SHP%.shp" %SPLEX% %SPLDB% %SPLSQL%

SET SHP=Zpm
SET SPLVT=vt_shpzpm
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%SHPDB%%SHP%', 'CP1252', 2154);"
IF EXIST "%SHPDB%%SHP%.shp" %SPLEX% %SPLDB% %SPLSQL%

:SCHEMA
ECHO Creation de la structure de la base de donnees

ECHO DEPLOIEMENT DU SCHEMA
SET FSQL=gracelite_schema.sql
%SPLEX% %SPLDB% < %FSQL%

:INSERTSHP
ECHO INSERTION DES DONNEES SHP DANS LES TABLES SPATIALITE
SET FSQL=gracelite_integ_shpcsv-in.sql
%SPLEX% %SPLDB% < %FSQL%

PAUSE
