@ECHO OFF

REM Gracelite/gracelite_dbinteg_create.bat
REM Version : 0.01
REM ALENO
REM CREATION DE LA BASE gracelite_integ.sqlite
REM Licence : GNU GPLv3
REM 23/06/2015 - SBY - aleno.eu : CREATION DU SCRIPT
REM Cible spatialite

ECHO CREATION DE LA BASE gracelite_integ.sqlite
PAUSE

:LAUNCH
CALL:CONFIG
CALL:BASE
CALL:SCHEMA
PAUSE
GOTO:EOF

:CONFIG
CALL config.bat
GOTO:EOF

:BASE
ECHO SUPPRESSION BASE
IF EXIST %GLDBINTEG% DEL /s %GLDBINTEG%

ECHO CREATION BASE
%GLSPLEX% %GLDBINTEG% "PRAGMA foreign_keys = ON;"

GOTO:EOF


:SCHEMA
ECHO GRACELITE - CREATION DE LA STRUCTURE DE LA BASE DE DONNEES
ECHO GRACELITE - CREATION DES LISTES
SET FSQL=%GLDBINTEGSCHEMA%\gracethd_1_lists.sql
%GLSPLEX% %GLDBINTEG% < %FSQL%
ECHO GRACELITE - INSERT VALEURS DANS LES LISTES
SET FSQL=%GLDBINTEGSCHEMA%\gracethd_2_insert.sql
%GLSPLEX% %GLDBINTEG% < %FSQL%
ECHO GRACELITE - CREATION DES TABLES
SET FSQL=%GLDBINTEGSCHEMA%\gracethd_3_tables.sql
%GLSPLEX% %GLDBINTEG% < %FSQL%
ECHO GRACELITE - AJOUT DES CHAMPS GEOMETRIQUES
SET FSQL=%GLDBINTEGSCHEMA%\gracethd_4_spatialite.sql
%GLSPLEX% %GLDBINTEG% < %FSQL%
ECHO GRACELITE - AJOUT DES INDEX
SET FSQL=%GLDBINTEGSCHEMA%\gracethd_5_index.sql
%GLSPLEX% %GLDBINTEG% < %FSQL%
ECHO GRACELITE - AJOUT DES SPECIFICITES
SET FSQL=%GLDBINTEGSCHEMA%\gracethd_6_specifique.sql
%GLSPLEX% %GLDBINTEG% < %FSQL%

GOTO:EOF